### ISSUE TITLE
Debug calculation of R^2 map when a subset of b-values is used

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SlicerProstate#2]
As reported by @ThieleK

> The only thing is that I think that the Quality of the fit volume might be incorrect when b-factors are 
> excluded. I added a few lines in my script to calculate the sum of squares and this calculating 
> corresponds with what you implemented to obtain the sum of squares 
> `double rms = optimizer->GetOptimizer()->get_end_error();  
> double SSerr = rms*rms*vectorVoxel.GetSize();`
> when I use all b-factors. However, if I exclude b=0, they deviate. Also, when we exclude b-factors, we 
> might not want to include those when  we determine the quality of the fit. So, I’m not sure if we want to 
> include this measure…

**Comment by fedorov** [comment]
@mehrtash can you take a look into this?

**Comment by mehrtash** [comment]
Fixed at https://github.com/SlicerProstate/SlicerProstate/commit/5698fc1fcc021d24d7cf9b6f9267abc63b7d5e87
