### ISSUE TITLE
Status : Completed with errors

### ISSUE THREAD

**Issue by louis10th** [SlicerProstate/SlicerProstate#23]
Hello.
I am trying to test out the quadedge surface mesher and segmentation smoother, but am getting this error with the prostate MR data found on the site link.

Warning: In d:\Slicer_r24735r\ITKv4\Modules\Core\Common\src\itklightobject.cxx,line206
lightObject : Trying to delete object with non-zero reference count.

The extension works fine on the stable release v 4.5.0-1, but returns this error on the same version of slicer I have built from the source.

Testing environment is windows 7 x64 and windows 10 x64.

Thanks in advance!

**Comment by fedorov** [comment]
Thanks for the report.

Note that the message you included is a warning, not the error. What is the error? Does Slicer crash or something else happens?

Does it work for you with the nightly (not stable) build?

**Comment by louis10th** [comment]
Thanks for the response.

The error message is displayed on the module panel. No surface model is created. 
The warning message is displayed in the console window.
The program doesn't crash, but will crash if I try to do  'clear scene'.

Are there any additional steps I could do to  get a more detailed message? It is in release mode.

I am having a problem with the nightly build not showing any extensions in the app shop. Also, when I manually try to add the paths of the extensions, it will fail to load them and disable it. That's why I went back to the stable version. Trying to figure out the problem.

**Comment by fedorov** [comment]
Thank you for the response. I will test the nightly and update the issue here with the result.

**Comment by fedorov** [comment]
I've just tested on Mac using today's nightly, and case 10 from the public dataset http://dx.doi.org/10.5281/zenodo.16396, and did not have any problems. No errors or warnings. I could even close the scene, and there still were no errors! Will test on Windows next.

**Comment by fedorov** [comment]
works fine on windows too, see screenshot below as a proof. No crash after closing the scene.

![image](https://cloud.githubusercontent.com/assets/313942/16994189/53953992-4e74-11e6-965d-57d07b4b488d.png)

I think first thing that should be investigated is why you don't see any extensions when you launch ExtensionManager for the nightly. Have you looked at the log? Could you report this issue to the slicer-users list?

I am not using Windows for development, so it is very very non-trivial for me to build Slicer on windows to test the build version. I suggest we focus on reproducing the issue in the nightly. What do you think?

**Comment by louis10th** [comment]
Should I look at the errror log (ctrl+0) or is there a separate log file saved somewhere? 
I will first try to rebuild the nightly just to be sure before I report the issue. 

This is the log from the stable build. Do you think something is wrong with my build?
[error log.txt](https://github.com/SlicerProstate/SlicerProstate/files/374290/error.log.txt)

**Comment by fedorov** [comment]
For the error log, probably the best is "Help > Report a bug"

No, rebuilding the nightly is not the first thing you should do. The nightly downloaded from slicer.org should work out of the box, and ExtensionManager should be populated. If that does not work, it is already a problem that should be reported.

**Comment by louis10th** [comment]
Yes, but the current most up-to-date build I have is from 2016-06-20. Thought it would be best to test out on the most recent nightly before reporting.

Do I have a to do a clean build to get the most updated nightly? I am not familiar with git. 
Thanks.

**Comment by fedorov** [comment]
The best is to reproduce the problem that does not require building Slicer.

In [this comment](https://github.com/SlicerProstate/SlicerProstate/issues/23#issuecomment-233967143) you say: "I am having a problem with the nightly build not showing any extensions in the app shop." This is the first problem you should report to the user list.

Do you have it working in the nightly or not?

**Comment by louis10th** [comment]
The problem has not been fixed. I have the nightly built from the 2016-06-20 revision. 
I will report it.

**Comment by fedorov** [comment]
The latest one is 2016-07-20.

Thanks!

**Comment by louis10th** [comment]
Yes. That is what I was trying to build. Do I have to regenerate using CMAKE and completely rebuild Slicer to get it to 2016-07-20? I was trying to find out a way to avoid this to save compile time. 

I have reported the issue with the 2016-06-20.

Thanks for the help.

**Comment by fedorov** [comment]
Here are step by step instructions of what you need to do:

1) go to http://download.slicer.org/
2) download Nightly windows build for your platform, as shown in the screenshot below
![image](https://cloud.githubusercontent.com/assets/313942/17020512/f1d40a48-4f0f-11e6-92b6-a332435d0299.png)
3) install Slicer
4) launch the installed version of Slicer
5) open Extension Manager
![image](https://cloud.githubusercontent.com/assets/313942/17020547/2969b57a-4f10-11e6-92c4-8bed76fac198.png)
6) if you do not see any extensions, this issue is unrelated to SlicerProstate, report it to the user list

**Comment by louis10th** [comment]
Extension works fine on Nightly Build r25241 (16-07-19) distributable version.

Found the issue with extensions not found in the built nightly versions.
The revision number is different from the distributable versions. (ra2b893b / 16-07-21)

Searching for this revision number here shows no extensions, hence the problem. Not sure if this was intended but will report.
http://slicer.kitware.com/midas3/slicerappstore?os=win&arch=amd64&revision=25241&category=&search=&layout=layout

Thanks.

**Comment by lassoan** [comment]
In general, if you build Slicer yourself then you need to build the extensions as well.
In special circumstances, if you can make sure you use the exact same build configuration (compiler, patches, external toolkits, build tools, etc) as the Slicer build machines then you may be able to reuse extensions that are built by Slicer build machines. Of course, this includes building Slicer from the same revision, from an SVN checkout (Slicer build machines identify Slicer versions based on SVN revision).

**Comment by fedorov** [comment]
Thank you @lassoan!

@louis10th to use the extension in Slicer you build on your own, the easiest would be to build the extension, and point Slicer to the directories with the scripts/libraries. Let us know if you need help on how to do this.

**Comment by louis10th** [comment]
Built the extension from current source code and added to Slicer built from source.
Works without a problem on  r25241 (16-07-19) and  (ra2b893b / 16-07-21).

Thanks for all the help!

**Comment by fedorov** [comment]
Perfect! Sorry for the confusion if I misunderstood your initial question. Happy that everything works.
