### ISSUE TITLE
method naming conflicts between mixins VTKObservationMixin and ParameterNodeObservationMixin

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SlicerProstate#37]
Since I implemented ParameterNodeObservationMixin by means of VTKObservationMixin

Both are similar but following a different approach.

Short version: 
- VTKObservationMixin: handles observers to events (mostly of other objects)
- ParameterNodeObservationMixin: handles observers that are listening to own events and allows the invocation of custom events thru the ParameterNode

More detailed:
- VTKObservationMixin provides a mechanism for each inherited class to add/handle outgoing observations. So it holds a list of observations to see which events (on specific objects) are observed. Once the inherited object is deleted, all outgoing observers will be removed
- ParameterNodeObservationMixin provides a mechanism to inheriting class to be able to invoke own events (by means of the parameterNode/vtkMRMLScriptedModuleNode) and to have control over observers which connected to the events of that class. Once the inherited object is deleted, all observers will be removed

I am going to rename methods so that they can be differentiated better. 

@fedorov: Any thoughts on this? Maybe it would be useful for the Slicer community?

**Comment by fedorov** [comment]
> Maybe it would be useful for the Slicer community?

I would bring this up for discussion at a Slicer dev hangout.
