### ISSUE TITLE
Warnings about calling obsolete SimpleITK functions

### ISSUE THREAD

**Issue by cpinter** [SlicerProstate/SlicerProstate#50]
When running DistanceMapBasedRegistration (through [SegmentRegistration](https://github.com/SlicerRt/SegmentRegistration)) the following warning messages appear in the python window. According to these messages some of the used functions will be removed in the future, so it would be good to migrate to their successors beofre that happens.

```
C:\Program Files\Slicer 4.8.0\bin\Python\sitkUtils.py:208: FutureWarning: 'removeOldMRMLNode' method is deprecated and will be removed in the future. Use sitkUtils.PushVolumeToSlicer method and slicer.util.setSliceViewerLayers methods instead.
  FutureWarning)
C:\Program Files\Slicer 4.8.0\bin\Python\sitkUtils.py:115: FutureWarning: 'CreateNewVolumeNode' method is deprecated and will be removed in the future.
  FutureWarning)
C:\Program Files\Slicer 4.8.0\bin\Python\sitkUtils.py:102: FutureWarning: 'checkVolumeNodeType' method is deprecated and will be removed in the future.
  FutureWarning)
C:\Program Files\Slicer 4.8.0\bin\Python\sitkUtils.py:170: FutureWarning: 'AddNodeToMRMLScene' method is deprecated and will be removed in the future.
  FutureWarning)
C:\Program Files\Slicer 4.8.0\bin\Python\sitkUtils.py:148: FutureWarning: 'removeOldMRMLNode' method is deprecated and will be removed in the future.
  FutureWarning)
```

**Comment by fedorov** [comment]
@cpinter looks like those are coming from sitkUtils, not from the code in SlicerProstate. Is this issue more appropriate for a discussion on the Slicer forum?

**Comment by fedorov** [comment]
Sorry, I keep rushing. I must be wrong. I will investigate. Sorry!

**Comment by cpinter** [comment]
These warnings come from calls like this
https://github.com/SlicerProstate/SlicerProstate/blob/master/DistanceMapBasedRegistration/DistanceMapBasedRegistration.py#L572

I don't know what are the replacement methods, but apparently for every obsolete method there is a new one that needs to be called. Also not sure when they will disappear, but it's good to keep this in mind to prevent these warnings from turning into errors one day.

**Comment by fedorov** [comment]
I agree, thank you for reporting this!

**Comment by fedorov** [comment]
Sorry for not fixing this - it's a very busy time with a proposal and other things, and I nearly completely abandoned development Oct-Nov, should be better after RSNA ...

**Comment by cpinter** [comment]
No urgency with this on my side!

**Comment by pieper** [comment]
Note that these deprecated calls are [now gone and the module doesn't work](https://github.com/Slicer/Slicer/commit/9da7419201c04129cdff3518f38e4c13247adefb).  I'm going to try to fix it but there's no migration guide that I can find and some of the replacements aren't instantly obvious.  I'll make a PR if I get a chance to fix it.

**Comment by fedorov** [comment]
Anyone is actually using this extension?! I admit I lost track of this completely...

**Comment by pieper** [comment]
I have a project where Csaba suggested I try this, but when I tried it turned out to be broken.  I have fixed the sitkUtils error and the module runs now, but I'm still trying to interpret the results to see if it's actually working.

**Comment by fedorov** [comment]
Thanks Steve! Let me know if you want to go over the module functionality together. I think I shared a public dataset along with the module in Sample Data - are you testing the module with that dataset?

![image](https://user-images.githubusercontent.com/313942/144928580-82ae5687-bb10-4a60-a1aa-ed0019157bcf.png)

**Comment by pieper** [comment]
I've been testing with some other data, but testing with something known to have worked would be better.  Did you have segmentations for those datasets?  I see the volumes are in SampleData.

**Comment by fedorov** [comment]
I thought I shared those too. I should have the segmentations, but I will need some time to  locate them.

**Comment by pieper** [comment]
If it's easy that would be great, but don't invest a lot of time.  I think the code is working but my use case is pushing the limits a bit.  I'm using it via the [SegmentRegistration](https://github.com/SlicerRt/SegmentRegistration) wrapper.

**Comment by fedorov** [comment]
I have never used the wrapper.

The screenshot shows segmentation contours, so I would expect segmentations were included. Do you know how to quickly locate where the data is downloaded from by SampleData? Maybe they were lost in migrating the data from Midas (or whatever was the name of the legacy system)?

**Comment by pieper** [comment]
From what I can tell Csaba's wrapper just allows you to use Segmentations and exports them to labelmaps internally.

I was able to load your MR/US data but didn't see any labelmaps.

I'm also exploring other options so for now this isn't in my critical path.  Just glad that it's working now.

**Comment by cpinter** [comment]
Thanks Steve for fixing the errors!

> just allows you to use Segmentations and exports them to labelmaps internally

Yes using segmentations is one half of the module's purpose. The other half is making sure the constraints that the SlicerProstate extension's modules pose are met with a wider range of input data (as I recall for example SlicerProstate expected the segment to be registered occupy a certain ratio in the center of the anatomy image etc).

And then the more specialized module (the MRI-US fusion one) automates parts of the process and is tailored to that specific scenario.
