### ISSUE TITLE
Preprint link is broken and article is paywalled

### ISSUE THREAD

**Issue by pieper** [SlicerProstate/SlicerProstate#55]
Since the publication database has been dead for a while and maybe never coming back, it would be good to provide a new copy of the preprint somewhere, perhaps as a release asset in this repo.

http://www.spl.harvard.edu/publications/item/view/2776

**Comment by pieper** [comment]
@fedorov

**Comment by fedorov** [comment]
Thank you for pointing this out! I replaced the link with the pubmed free version. It is unfortunate how the publications database just disappeared without any warning...

**Comment by lassoan** [comment]
>  It is unfortunate how the publications database just disappeared without any warning...

I agree. @pieper would if be possible to just export the files and an sql dump of the database? We could then easily convert the database content to a markdown (file listing all the papers on a single page) and publish everything using github pages.

**Comment by pieper** [comment]
I'm not sure - I'll check.
